version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "idaho"
    reviewers:
      - "idaho"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
    labels:
      - "npm"
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "disabled"
    versioning-strategy: increase