# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - fix
        - bug
    - title: Translations 🌍
      labels:
        - translations
    - title: Other Changes
      labels:
        - "*"
