name: 🐞 Bug Report
description: Create a report to help us improve
title: "[Bug]: <title>"
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Requirements
      options:
        - label: I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
          required: true
        - label: I did a search to see if there is a similar issue or if a pull request is open.
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Context
      description: |
        If your issue is about a certain type of entity, please provide the entity state/attribute. You can find it in the [developer tools](https://my.home-assistant.io/redirect/developer_states/). Otherwise, you can leave this section blank.
      value: |
        YAML state
        ```yaml

        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **Brower**: Chrome
          - **HA Version**: 2022.11.0
          - **TrashCard**: 1.3.0
      value: |
        - Browser:
        - HA Version:
        - TrashCard:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Debug data
      description: |
        Copy the available debug data you from the card. You can get those debug information to update to at least version 2.0.0-beta.4.
        Edit the trash-card item you have added, open the yaml editor and add `debug: true` to it. 
        After that you will see some debug information. At the right corner you will see a copy icon. Click on this and icon to
        copy the debug information to you clipboard and paste them in here. After that you can remove the added debug line from
        your yaml configuration.
      render: json
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
