name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install dependencies
      run: |
        npm ci
    - name: Building
      run: |
        npm run build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
      run: npx semantic-release